Des 39 create login validation mongo db
DanielCalleCO/Regresemos_a_nuestra_casa_UI pull request #12
Opened 2023-02-27 16:23 UTC by Daniielmayo

Implementation of work done so far

2023-02-27 16:28 UTC, Daniielmayo reviewed
review of the changes presented

2023-02-27 17:10 UTC, DanielCalleCO requested changes
Make sure you review my comments before pushing again Dani. Good job!

2023-02-27 17:10 UTC, DanielCalleCO commented on src/auth/sesionPageNabvar/SesionPageNavbar.jsx
> +// import { Validacion} from '../../middleware/Validacion'
Are you using this import? Or will be used in the future? If not, is better to delete it to clean the code

2023-02-27 17:10 UTC, DanielCalleCO commented on src/components/organims/carousel/Slideshow.jsx
> -   console.log(slideshow)
IDK if you missed it or this `console.log` has any function in our code? Try to don't push unnecessary comments or `console.log` if it's not necessary either.

2023-02-27 17:10 UTC, DanielCalleCO commented on src/components/organims/carousel/Slideshow.jsx
>      //Comprobamos que slideshow tenga elementos
Good, but let your code in the same language (English mainly) :)

2023-02-27 17:10 UTC, DanielCalleCO commented on src/components/routes/AppRoutes.jsx
> +
It is necessary to use multiple lines to separate imports? Try to use just one line to separate it and keep the code clean ;)

2023-02-27 17:10 UTC, DanielCalleCO commented on src/helpers/getEnvVariable.js
> +//* varibles de entorno
English

2023-02-27 17:10 UTC, DanielCalleCO commented on src/helpers/getEnvVariable.js
> +    //     ...process.env.REACT_APP_API_URL
Describe why you used a comment... or just delete it before push...

2023-02-27 17:10 UTC, DanielCalleCO commented on src/hooks/useAuthStore.js
> +        //*Propiedades
English

2023-02-27 17:10 UTC, DanielCalleCO commented on src/hooks/useAuthStore.js
> +        //*Metodos
English

2023-03-08 19:00 UTC, Daniielmayo commented on src/auth/sesionPageNabvar/SesionPageNavbar.jsx
> +// import { Validacion} from '../../middleware/Validacion'
It is an import that will be used for user validation and to be able to close the ticket that is blocked

2023-03-08 19:18 UTC, Daniielmayo commented on src/helpers/getEnvVariable.js
> +    //     ...process.env.REACT_APP_API_URL
This is part of the code debugging to find the ticket error DES-39Create Login validation

2023-03-08 20:38 UTC, DanielCalleCO commented on src/auth/sesionPageNabvar/SesionPageNavbar.jsx
> +// import { Validacion} from '../../middleware/Validacion'
OK, so add a comment before it (if you think necessary) to explain why you pushed a commented line

2023-03-08 20:39 UTC, DanielCalleCO commented on src/components/organims/carousel/Slideshow.jsx
> -   console.log(slideshow)
@Daniielmayo any comment about this?

2023-03-08 20:45 UTC, DanielCalleCO commented on origen/ayudantes/getEnvVariable.js
> +//* Environment Variables
Environment variables (without capital "V")

2023-03-08 20:53 UTC, DanielCalleCO requested changes
When you change all the comments, let me know on slack to review your code again.

2023-03-08 20:53 UTC, DanielCalleCO commented on src/components/organims/carousel/Slideshow.jsx
> +    const following = ({children})=>{
I think you may use "next" instead of "following"... Go to your VSC and right click over `following` and then click _Rename Symbol_ and verify every time you used `following`, now is `next`

2023-03-08 20:53 UTC, DanielCalleCO commented on src/components/routes/AppRoutes.jsx
> -             //Todo Rutas publicas
Public routes*

2023-03-08 23:31 UTC, abdulflorez approved these changes

2023-03-08 23:32 UTC, merged