Des 65 dev make responsive learning path
DanielCalleCO/Regresemos_a_nuestra_casa_UI pull request #31
Opened 2023-03-23 18:36 UTC by Daniielmayo

2023-03-23 20:34 UTC, DanielCalleCO requested changes

2023-03-23 20:34 UTC, DanielCalleCO commented on src/components/routes/AppRoutes.jsx
> +import { ComponentRouteVideo } from '../organims/home/learningPath/contentViderRoute/contentVideoRoute/ComponentRouteVideo';
Review the first "contentVide**o**Route" not "contentViderRoute"

2023-03-24 13:37 UTC, DanielCalleCO commented on src/components/routes/AppRoutes.jsx
> +import { ComponentRouteVideo } from '../organims/home/learningPath/contentViderRoute/contentVideoRoute/ComponentRouteVideo';
OK, next time in English. Thanks, Dany!

2023-03-24 13:37 UTC, DanielCalleCO approved these changes

2023-03-24 15:45 UTC, SthefaniaEcheverry approved these changes

2023-04-25 13:23 UTC, abdulflorez approved these changes

2023-04-25 13:27 UTC, merged