Des 39 create login validation
DanielCalleCO/Regresemos_a_nuestra_casa_UI pull request #34
Opened 2023-04-21 18:18 UTC by Daniielmayo

2023-04-21 20:07 UTC, DanielCalleCO requested changes

2023-04-24 13:48 UTC, Daniielmayo commented on src/auth/sesionPageNabvar/SesionPageNavbar.jsx
> +  const loginSubmit =  (event) => {
I did not run Prettier or Slint since for some reason it changes parts of the code and generates errors in the operation

2023-04-24 18:50 UTC, DanielCalleCO commented on src/auth/sesionPageNabvar/SesionPageNavbar.jsx
> +  const loginSubmit =  (event) => {
Ok, but the idea is to run it, not to avoid it... Because that space before (event) can be solved with an esLint or prettier check... That is why we decided to install it on our project, to avoid that kind of problem with the format of our code. So please, run esLint, and Prettier, and try configuring them to work with our project. If you need help, just let me know and we can meet

2023-04-24 18:52 UTC, DanielCalleCO requested changes

2023-04-24 18:52 UTC, DanielCalleCO commented on src/models/routes.jsx
> +    FAVORIT: '/favorite',
**FAVORITE:** too

2023-04-25 20:19 UTC, DanielCalleCO approved these changes

2023-04-25 20:20 UTC, abdulflorez approved these changes

2023-04-25 20:20 UTC, merged