Des 85 dev make responsive path content
DanielCalleCO/Regresemos_a_nuestra_casa_UI pull request #38
Opened 2023-05-08 16:48 UTC by SthefaniaEcheverry

Responsive view added for path content
Check details on:
(DES-85)[Responsive view for](https://danielcalleco.atlassian.net/jira/software/projects/DES/boards/4?selectedIssue=DES-85)

2023-05-08 16:52 UTC, abdulflorez approved these changes
Lgtm

2023-05-08 17:17 UTC, DanielCalleCO requested changes
Please review the comments! You did it soooo good! Congrats!

2023-05-08 17:17 UTC, DanielCalleCO commented on src/App.css
> +  --yellow: #fad047;
did you run `pre-push` command BEFORE pushing the branch?

2023-05-08 17:17 UTC, DanielCalleCO commented on src/components/molecules/homeRoute/componentCenter/ComponentCenter.jsx
> +            <p className="classRoomInfo-questionsTwo">¿De quiénes venimos? </p>
Is this space after 'venimo? ' necessary?

2023-05-08 17:17 UTC, DanielCalleCO commented on src/components/organims/home/homeViewFavorit/HomeViewFavorit.jsx
> +    <div className="container-homeViewFavorite">HomeViewFavorit</div>
Favorit**E**

2023-05-08 18:42 UTC, Daniielmayo approved these changes

2023-05-09 12:59 UTC, Daniielmayo approved these changes

2023-05-09 20:19 UTC, abdulflorez approved these changes
LGTM, nice job

2023-05-09 20:21 UTC, merged